artifact_location: file:///C:/Users/saalzamil/Desktop/Journey/phonebook-analytics/ai/runs/mlflow/960964123010920234
creation_time: 1777892426974
experiment_id: '960964123010920234'
last_update_time: 1777892426974
lifecycle_stage: active
name: runs/classify
trace_location: null
workspace: default
